# Generated by Django 4.2.3 on 2023-07-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_alter_students_email"),
    ]

    operations = [
        migrations.AlterModelManagers(name="students", managers=[],),
    ]
