# Generated by Django 4.1.1 on 2023-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_complaintform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintform",
            name="student",
            field=models.CharField(max_length=200),
        ),
    ]
