# Generated by Django 4.2.3 on 2023-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_alter_students_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="matric_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
